title: Vintage Computer Nordic - DEC
description: Restoring Vintage DEC Machines
theme: just-the-docs

url: https://vintagecomputernordic.github.io

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/dec_logo.png"

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
